### PR TITLE
Added Find By ButtonText, ButtonTextPartial, LabelText

### PR DESCRIPTION
**Pull request by JP-3**

### CODE REVIEW

**Comment by bbaia** [comment]
This has nothing to do with Angular. It should be added to an helper library instead.

**Comment by JP-3** [comment]
Thanks, I was thinking of doing that anyway but didn't think to look a the
'ng-' angular aspect.  Much appreciated on getting back to me as I didn't
realize it, I hope to get back into this when we go back to the web.

**Comment by JP-3** [comment]
OK, i'm going to get back into this stuff this week I think so I decided to look back at what I was doing. I can see the Button is angular as it has the ng.click but rather then spying to see what the properties were I found it easier to just look for the text of the button as I can just read it off the page and for the Label you can see both the angular models are identical for both labels, except for the label itself.  Can you let me know what your thoughts are if you have a minute.  Thanks Bruno  

<button class="btn btn-primary" ng-click="SearchController.search()">
                               “Search”
<label type="button" class="btn btn-default ng-pristine ng-valid active" ng-model=" SearchController.toggleOption" btn-radio="'not_linked'">Not Linked</label>

<label type="button" class="btn btn-default ng-pristine ng-valid" ng-model="SearchController.toggleOption" btn-radio="'linked'">Linked</label>

**Comment by bbaia** [comment]
I don't get it.
Why don't you  use the classic WebDriver code for that ?
Ex: http://sqa.stackexchange.com/questions/2696/selenium-how-to-identify-the-button-webelement/2697

**Comment by disophisis** [comment]
if I'm understanding JP-3 correctly, it may be best to just do as @bbaia said above and use classic WebDriver.  I find that By.CssSelector works very well for these types of things.  Finding all buttons: FindElements(By.CssSelector("button"))

**Comment by JP-3** [comment]
I was just porting code over from the "https://github.com/angular/protractor"
project to keep my way of finding things similar and reuse what was already
in the other project.

**Pull request closed without merging**
