### PR TITLE
Added ability to use NgBy methods as CustomeTypeFilters in Selenium FindsBy for PageObjects

### PR DESCRIPTION
**Pull request by matgardon**
This enables use cases of the form : 

[FindsBy(How = How.Custom, CustomFinderType = typeof(NgByRepeater), Using = "item in
collection")]
public IList<IWebElement> items { get; set; }

Side effect : JavaScriptBy needs to be public

Additional change : bounced Selenium.WebDriver to 2.47. (Can be rollbacked to be done separatly).

### CODE REVIEW

**Comment by robertfaheymoonpig** [comment]
Any chance this can be merged, and a release made?

**Comment by bbaia** [comment]
Yes. I planned a new version this month. Stay tuned !

**Comment by bbaia** [comment]
Thanks @matgardon for the contribution !

**Comment by sergueik** [comment]
Hello Bruno,

I forked your project about half a year ago and developed a lot of practical examples and few functional enhancements to it. 

I do small commits in https://github.com/sergueik/powershell_selenium/tree/master/csharp/protractor-net and periodically collated commits to my fork, https://github.com/sergueik/protractor-net
I published my work examples on codeproject:
http://www.codeproject.com/Articles/1066968/Developing-Protractor-tests-in-Csharp-or-Java
I rearranged c# source somewhat - this is one reason I was not making PR until now. I tried to reach you on twitter, but you never replied.

I also develop jProtracor, which is a close twin on Protractor-net, but uses Java client bindings.
I develop feature or test  in both projects in parallel.


I made fer hundred commits to those projects by now, (e.g. approx a hundred unit and integration tests using small and mid-size Angular pages and sites
and have some positive feedback from testers

I appreciate if you take a look at my projects and advise if  
a PR is possible and if you prefer my project layout or your original one.
Thanks,
Serguei Kouzmine

**Pull request closed without merging**
