### PR TITLE
Feature: Supports PageFactory implementation

### PR DESCRIPTION
**Pull request by mvpspl619**
Added code to support PageFactory implementation. Added tests to verify the functionality didn't break. Please review and let me know.

### CODE REVIEW

**Comment by goneale** [comment]
Did he ever get back to you? I wish to use this

**Comment by mvpspl619** [comment]
@goneale Nope :(

**Comment by bbaia** [comment]
When I looked to this pull request, there was too much code duplicated (see first commit), but looks like you fixed it later with another commit.
Could you plz rebase your branch and combine some commits to make it clearer ?

**Comment by mvpspl619** [comment]
That should be possible. I will clean it up.

-----Original Message-----

**Comment by mvpspl619** [comment]
I am closing this PR. Will create a new one with proper commits.

**Comment by bbaia** [comment]
You dont need tout. Just re-initialize your master.
- fetch from origin
- reset hard your master on origin/master
- make your changes ans commit
- force push

**Comment by mvpspl619** [comment]
I am not familiar with merging in git. I'll see these options. Thanks.

-----Original Message-----

**Pull request closed without merging**
